app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, ValidationError, TextField, TextAreaField, PasswordField, ValidationError, StringField
from wtforms.fields.html5 import TelField
from wtforms.validators import DataRequired, Email, EqualTo


#main contact form on contact us page
class ContactForm(FlaskForm):
    
    name = TextField('Name', validators=[DataRequired()])
    email = TextField('Email', validators=[DataRequired(), Email()])
    phone = TelField('Phone')
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Submit')
    
#login form on login page         
class LoginForm(FlaskForm):
    
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import flash, redirect, render_template, url_for, abort
from flask_login import login_required, current_user, login_user, logout_user


from . import home
from forms import ContactForm, LoginForm
from .. import db
from ..models import User, Checksheet, Contact, Announcement, ImportantDate
from app.decorators import check_confirmed
from app.email import send_email

#route to contact page with contact form
@home.route('/contact', methods=['GET', 'POST'])
def contact():
    
    form = ContactForm()
    if form.validate_on_submit():
        #add send email to admin functionality
        contact = Contact(
            name = form.name.data,
            email = form.email.data,
            phone = form.phone.data,
            message = form.message.data,
        )
        db.session.add(contact)
        db.session.commit()
        
        #send confirmation email to user
        html = render_template('home/confirm_contact.html', name=contact.name, email=contact.email, phone=contact.phone, message=contact.message)
        subject = "UMW Honors - Thank you for contacting us!"
        send_email(contact.email, subject, html)
        
        #send email to admin
        admin_email = 'umwhonorsperson@gmail.com'
        html_admin = render_template('home/admin_contact.html', name=contact.name, email=contact.email, phone=contact.phone, message=contact.message)
        subject2 = "UMW Honors - You have a message from the UMW Honors Portal!"
        send_email(admin_email, subject2, html_admin)
        
        #change to redirect to success page
        flash('Contact form successfully submitted!', 'success')
        return redirect(url_for('home.contact'))
    
    return render_template('home/contact.html', title="Contact Us", form=form)
    
#route to student user's dashboard
@home.route('/mypage')
@login_required
@check_confirmed
def mypage():
    
    announcements = Announcement.query.order_by(Announcement.created.desc())
    dates = ImportantDate.query.order_by(ImportantDate.date_time)
    
    return render_template('home/mypage.html', title="My Page", announcements=announcements, dates=dates)


#route to student user's checksheet
@home.route('/checksheet')
@login_required
@check_confirmed
def checksheet():
    user_honors_id = current_user.honors_id
    user_checksheet = Checksheet.query.filter_by(honors_id=user_honors_id).first()
    dates = ImportantDate.query.order_by(ImportantDate.date_time)
   
    return render_template('home/view-checksheet.html', title="My Checksheet", checksheet=user_checksheet, dates=dates)


#route to admin user's dashboard
@home.route('/admin/dashboard')
@login_required
@check_confirmed
def admin_dashboard():

    if not current_user.is_admin:
        abort(403)
        
    announcements = Announcement.query.order_by(Announcement.created.desc())
    dates = ImportantDate.query.order_by(ImportantDate.date_time)
    
    return render_template('home/admin_dashboard.html', title="Dashboard", announcements=announcements, dates=dates)
    

app/templates/home/admin_contact.html
<p>You have a new message!</p>
<p>Here is the message you received: </p>

<p>{{ name }}</p>
<p>{{ email }}</p>
<p>{{ phone }}</p>
<p>{{ message }}</p>

app/templates/home/admin_dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base-layout.html" %}
{% block content %}

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}
                    <small>UMW Honors Program</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="/">Home</a>
                    </li>
                    <li class="active">{{ title }}</li>
                </ol>
            </div>
        </div>
        
        <!-- Menu Buttons -->
        <div class="row">
            <div class="col-lg-12">
                <div class="btn-group">
                    {% if current_user.is_authenticated %}
                        {% if current_user.is_admin %}
                                <a href="{{ url_for('admin.upload') }}"><button type="button" class="btn btn-default">Upload</button></a>
                                <a href="{{ url_for('admin.search') }}"><button type="button" class="btn btn-default">Search</button></a>
                                <a href="{{ url_for('admin.add_announcement') }}"><button type="button" class="btn btn-default">Add Announcement</button></a>
                                <a href="{{ url_for('admin.add_date') }}"><button type="button" class="btn btn-default">Add Date</button></a>
                        {% endif%}
                    {% endif %}
                </div>
            </div>
        </div>
        
        <!-- Body -->
        <div class="row">
            <div class="col-lg-12">
                <br />
                {{ utils.flashed_messages() }}
                <br /> 
                
                <!-- Edit Announcements -->
                <div class="col-lg-6">
                    <h3>Announcements</h3>
                    {% if announcements %}
                    {% for announcement in announcements %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-md-10">
                                    <h4>{{ announcement.title }}</h4>
                                </div>
                                <div class="col-md-2">
                                    <a href="{{ url_for('admin.edit_announcement', id=announcement.id) }}"><span class="fa fa-pencil-square-o"></span></a>
                                    <a href="{{ url_for('admin.delete_announcement', id=announcement.id) }}"><span class="fa fa-trash-o"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <p>{{ announcement.description }}</p>
                            <p>Created: {{ announcement.created.strftime('%b %d, %Y')}}</p>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>

                <!-- Edit Dates -->
                <div class="col-lg-6">
                    <h3>Important Dates</h3>
                    {% if dates %}
                    {% for date in dates %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-md-10">
                                    <h4>{{ date.title }}</h4>
                                </div>
                                <div class="col-md-2">
                                    <a href="{{ url_for('admin.edit_date', id=date.id) }}"><span class="fa fa-pencil-square-o"></span></a>
                                    <a href="{{ url_for('admin.delete_date', id=date.id) }}"><span class="fa fa-trash-o"></span></a>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <p>{{ date.date_time.strftime('%b %d, %Y') }}</p>
                            <p>{{ date.info }}</p>
                        </div>
                    </div>
                    {% endfor %}
                    
                    {% else %}
                        <p>There are no dates to display.</p>
                    {% endif %}
                    
                    
                </div>

            </div>
            
        </div>

{% endblock %}

app/templates/home/confirm_contact.html
<p>Thank you for contacting the UMW Honors Program!</p>
<p>Here is the message you sent: </p>

<p>{{ name }}</p>
<p>{{ email }}</p>
<p>{{ phone }}</p>
<p>{{ message }}</p>

<br />
<p>We will be in touch with you regarding your message shortly!</p>

app/templates/home/contact.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base-layout.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}
                    <small>UMW Honors Program</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="/">Home</a>
                    </li>
                    <li class="active">{{ title }}</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                {{ utils.flashed_messages() }}
                <h3>Send us a Message</h3>
                {{ wtf.quick_form(form) }}
            </div>
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p>
                    duPont Hall Room 210<br>
                </p>
                <p><i class="fa fa-phone"></i> 
                    <abbr title="Phone">Phone</abbr>: (540)-654-1716</p>
                <p><i class="fa fa-envelope-o"></i> 
                    <abbr title="Email">Email</abbr>: <a href="mailto:kslunt@umw.edu">kslunt@umw.edu</a>
                </p>
                <p><i class="fa fa-clock-o"></i> 
                    <abbr title="Hours">Hours</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    
{% endblock %}

app/templates/home/index.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base-layout.html" %}
{% block content %}
    <img class="img-responsive" src="../static/img/dupont.jpg">

    <!-- Main jumbotron showing welcome message and login form -->
    <div class="container jumbotron">
      <div class="row">
        <div class="col-lg-6">
          <h1>Welcome! </h1>
          <p>Are you a UMW Honors Program student? <br />Create an account now to view your checksheet <br /> and track your progress!</p>
          <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}" role="button">Create an account here! &raquo;</a></p>
        </div>
        <div class="col-lg-6">
          <div class="panel panel-default" style="color: #000;">
            <div class="panel-body">
              <p>Already have an account? Login here</p>
                {{ utils.flashed_messages() }}
              <br />
              {{ wtf.quick_form(formLogin) }}
              <br />
              <a href="{{ url_for('auth.forgotpassword') }}">Forgot Password</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>Honors Program Information</h2>
          <br>
          <!--
          <ul>
            </li><a href="http://academics.umw.edu/honorsprogram/">Honors Program Home Page</a></li>
          </ul>
          <ul>
            </li><a href="http://academics.umw.edu/honorsprogram/approved-honors-courses/">Honors Program Courses</a></li>
          </ul>
          <ul>
            </li><a href="https://banner.umw.edu/prod/umw_clas.p_displayallnocount">UMW Schedule of Courses</a></li>
          </ul>
          <ul>
            </li><a href="http://academics.umw.edu/honorsprogram/files/2017/01/application_s17.pdf">Honors Program Application</a></li>
          </ul> -->
          
          <a href="http://academics.umw.edu/honorsprogram/" class="btn btn-info" role="button">Honors Program Home Page</a>
          <a href="http://academics.umw.edu/honorsprogram/approved-honors-courses/" class="btn btn-info" role="button">Honors Program Courses</a>
          <br>
          <br>
          <a href="https://banner.umw.edu/prod/umw_clas.p_displayallnocount" class="btn btn-info" role="button">UMW Schedule of Courses</a>
          <a href="http://academics.umw.edu/honorsprogram/files/2017/01/application_s17.pdf" class="btn btn-info" role="button">Honors Program Application</a>


        </div>
        <div class="col-md-4">
          
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2>Important Dates</h2>
            </div>
            
            <div class="panel-body">
              {% if dates %}
                {% for date in dates %}
                <h4><strong>{{date.date_time.strftime('%b %d, %Y') }}</strong></h4>
                <p><strong>{{date.title}}</strong></p>
                <li>{{date.info}}</li>
                <p></p>
                <p></p>
                {% endfor %}
              {% else %}
                <p>There are no dates to display.</p>
              {% endif %}
            </div>
            
          </div>
          
        </div>
        
      </div>
    </div>
{% endblock %}

app/templates/home/mypage.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "sidebar-layout.html" %}
{% block content %}

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}
                    <small>UMW Honors Program</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="/">Home</a>
                    </li>
                    <li class="active">{{ title }}</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h2>Hello, {{ current_user.username }}</h2>
                <br />
                {{ utils.flashed_messages() }}
                <br />
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('home.checksheet') }}">View Checksheet</a></p>
                <div class="page-header"><h2>Announcements</h2></div>
                
                {% if announcements %}
                {% for announcement in announcements %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>{{ announcement.title }}</h4>
                    </div>
                    <div class="panel-body">
                        <p>{{ announcement.description }}</p>
                        <p>Created: {{ announcement.created.strftime('%b %d, %Y') }}</p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        
{% endblock %}

app/templates/home/view-checksheet.html
{% extends "sidebar-layout.html" %}
{% block content %}

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}
                    <small>UMW Honors Program</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="/">Home</a>
                    </li>
                    <li class="active">{{ title }}</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">

  <h3><font color=5b6ab9>Honors Designated Course Requirements</font></h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Course Name</th>
      <th>Course Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row" width="30%">HONR 100</th>
      <td>{{ checksheet.fsemHN }}</td>
      <td>{{ checksheet.fsemHNDate }}</td>
    </tr>
    <tr>
      <th scope="row">HN Course 1</th>
      <td>{{ checksheet.hnCourse1 }}</td>
      <td>{{ checksheet.hnCourse1Date }}</td>
    </tr>
    <tr>
      <th scope="row">HN Course 2</th>
      <td>{{ checksheet.hnCourse2 }}</td>
      <td>{{ checksheet.hnCourse2Date }}</td>
    </tr>
    <tr>
      <th scope="row">HN Course 3</th>
      <td>{{ checksheet.hnCourse3 }}</td>
      <td>{{ checksheet.hnCourse3Date }}</td>
    </tr>
    <tr>
      <th scope="row">HN Course 4</th>
      <td>{{ checksheet.hnCourse4 }}</td>
      <td>{{ checksheet.hnCourse4Date }}</td>
    </tr>
    <tr>
      <th scope="row">HN Course 5</th>
      <td>{{ checksheet.hnCourse5 }}</td>
      <td>{{ checksheet.hnCourse5Date }}</td>
    </tr>
    <tr>
      <th scope="row">HONR 201</th>
      <td>{{ checksheet.hon201 }}</td>
      <td>{{ checksheet.hon201Date }}</td>
    </tr>
    <tr>
      <th scope="row">Research Course</th>
      <td>{{ checksheet.researchCourse }}</td>
      <td>{{ checksheet.researchCourseDate }}</td>
    </tr>
     <tr>
      <th scope="row">Capstone Course</th>
      <td>{{ checksheet.capstoneCourse }}</td>
      <td>{{ checksheet.capstoneCourseDate }}</td>
    </tr>
  </tbody>
</table>

  <h3><font color=5b6ab9>Co-Curricular Requirements</font></h3>

  <table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Co-Curricular Name</th>
      <th>Co-Curricular Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row" width="30%">Co-Curricular 1</th>
      <td>{{ checksheet.coCur1 }}</td>
      <td>{{ checksheet.coCurDate1 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 2</th>
      <td>{{ checksheet.coCur2 }}</td>
      <td>{{ checksheet.coCurDate2 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 3</th>
      <td>{{ checksheet.coCur3 }}</td>
      <td>{{ checksheet.coCurDate3 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 4</th>
      <td>{{ checksheet.coCur4 }}</td>
      <td>{{ checksheet.coCurDate4 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 5</th>
      <td>{{ checksheet.coCur5 }}</td>
      <td>{{ checksheet.coCurDate5 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 6</th>
      <td>{{ checksheet.coCur6 }}</td>
      <td>{{ checksheet.coCurDate6 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 7</th>
      <td>{{ checksheet.coCur7 }}</td>
      <td>{{ checksheet.coCurDate7 }}</td>
    </tr>
    <tr>
      <th scope="row">Co-Curricular 8</th>
      <td>{{ checksheet.coCur8 }}</td>
      <td>{{ checksheet.coCurDate8 }}</td>
    </tr>
     
  </tbody>
</table>

  <h3><font color=5b6ab9>Honors Portfolio Requirements</font></h3>

  <table class="table table-bordered">

  <tbody>
    <tr>
      <th scope="row">HONR Portfolio 1</th>
      <td width="70%">{{ checksheet.portfolio1 }}</td>
    </tr>
    <tr>
      <th scope="row">HONR Portfolio 2</th>
      <td width="70%">{{ checksheet.portfolio2 }}</td>
    </tr>
    <tr>
      <th scope="row">HONR Portfolio 3</th>
      <td width="70%">{{ checksheet.portfolio3 }}</td>
    </tr>
    <tr>
      <th scope="row">HONR Portfolio 4</th>
      <td width="70%">{{ checksheet.portfolio4 }}</td>
    </tr>
     
  </tbody>
</table>

  <h3><font color=5b6ab9>Additional Requirements</font></h3>

  <table class="table table-bordered">

  <tbody>
    <tr>
      <th scope="row">Initial Essay Date</th>
      <td width="70%">{{ checksheet.initialEssayDate }}</td>
    </tr>
    <tr>
      <th scope="row">Leadership</th>
      <td width="70%">{{ checksheet.leadership }}</td>
    </tr>
    <tr>
      <th scope="row">Mentoring</th>
      <td width="70%">{{ checksheet.mentoring }}</td>
    </tr>
    <tr>
      <th scope="row">Exit Interview</th>
      <td width="70%">{{ checksheet.exit}}</td>
    </tr>
    <tr>
      <th scope="row">Initial Essay Date</th>
      <td width="70%">{{ checksheet.initialEssayDate }}</td>
    </tr>
  </tbody>
</table>
            </div>
        </div>
        
{% endblock %}

app/templates/home/view-search-results.html
{% extends "sidebar-layout.html" %}
{% block content %}

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ title }}
                    <small>UMW Honors Program</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="/">Home</a>
                    </li>
                    <li class="active">{{ title }}</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header"><h2>{{ title }}</h2></div>
                
                {% if results %}
                <ol>
                {% for result in results %}
                    <li><a href="{{ url_for('admin.view_student_checksheet', honorsid=result.honors_id) }}">{{ result.lastName }}, {{ result.firstName }}</a></li>
                {% endfor %}
                </ol>
                {% else %}
                    <p>There are no results to display.</p>
                {% endif %}
            </div>
        </div>
        
{% endblock %}